// AUTO-GENERATED by scripts/generate-sdk-types.ts — do not edit by hand.
import type { z } from 'zod/v4'
import {
  ModelUsageSchema,
  OutputFormatTypeSchema,
  BaseOutputFormatSchema,
  JsonSchemaOutputFormatSchema,
  OutputFormatSchema,
  ApiKeySourceSchema,
  ConfigScopeSchema,
  SdkBetaSchema,
  ThinkingAdaptiveSchema,
  ThinkingEnabledSchema,
  ThinkingDisabledSchema,
  ThinkingConfigSchema,
  McpStdioServerConfigSchema,
  McpSSEServerConfigSchema,
  McpHttpServerConfigSchema,
  McpSdkServerConfigSchema,
  McpServerConfigForProcessTransportSchema,
  McpClaudeAIProxyServerConfigSchema,
  McpServerStatusConfigSchema,
  McpServerStatusSchema,
  McpSetServersResultSchema,
  PermissionUpdateDestinationSchema,
  PermissionBehaviorSchema,
  PermissionRuleValueSchema,
  PermissionUpdateSchema,
  PermissionDecisionClassificationSchema,
  PermissionResultSchema,
  PermissionModeSchema,
  HookEventSchema,
  BaseHookInputSchema,
  PreToolUseHookInputSchema,
  PermissionRequestHookInputSchema,
  PostToolUseHookInputSchema,
  PostToolUseFailureHookInputSchema,
  PermissionDeniedHookInputSchema,
  NotificationHookInputSchema,
  UserPromptSubmitHookInputSchema,
  SessionStartHookInputSchema,
  SetupHookInputSchema,
  StopHookInputSchema,
  StopFailureHookInputSchema,
  SubagentStartHookInputSchema,
  SubagentStopHookInputSchema,
  PreCompactHookInputSchema,
  PostCompactHookInputSchema,
  TeammateIdleHookInputSchema,
  TaskCreatedHookInputSchema,
  TaskCompletedHookInputSchema,
  ElicitationHookInputSchema,
  ElicitationResultHookInputSchema,
  ConfigChangeHookInputSchema,
  InstructionsLoadedHookInputSchema,
  WorktreeCreateHookInputSchema,
  WorktreeRemoveHookInputSchema,
  CwdChangedHookInputSchema,
  FileChangedHookInputSchema,
  ExitReasonSchema,
  SessionEndHookInputSchema,
  HookInputSchema,
  AsyncHookJSONOutputSchema,
  PreToolUseHookSpecificOutputSchema,
  UserPromptSubmitHookSpecificOutputSchema,
  SessionStartHookSpecificOutputSchema,
  SetupHookSpecificOutputSchema,
  SubagentStartHookSpecificOutputSchema,
  PostToolUseHookSpecificOutputSchema,
  PostToolUseFailureHookSpecificOutputSchema,
  PermissionDeniedHookSpecificOutputSchema,
  NotificationHookSpecificOutputSchema,
  PermissionRequestHookSpecificOutputSchema,
  CwdChangedHookSpecificOutputSchema,
  FileChangedHookSpecificOutputSchema,
  SyncHookJSONOutputSchema,
  ElicitationHookSpecificOutputSchema,
  ElicitationResultHookSpecificOutputSchema,
  WorktreeCreateHookSpecificOutputSchema,
  HookJSONOutputSchema,
  PromptRequestOptionSchema,
  PromptRequestSchema,
  PromptResponseSchema,
  SlashCommandSchema,
  AgentInfoSchema,
  ModelInfoSchema,
  AccountInfoSchema,
  AgentMcpServerSpecSchema,
  AgentDefinitionSchema,
  SettingSourceSchema,
  SdkPluginConfigSchema,
  RewindFilesResultSchema,
  APIUserMessagePlaceholder,
  APIAssistantMessagePlaceholder,
  RawMessageStreamEventPlaceholder,
  UUIDPlaceholder,
  NonNullableUsagePlaceholder,
  SDKAssistantMessageErrorSchema,
  SDKStatusSchema,
  SDKUserMessageSchema,
  SDKUserMessageReplaySchema,
  SDKRateLimitInfoSchema,
  SDKAssistantMessageSchema,
  SDKRateLimitEventSchema,
  SDKStreamlinedTextMessageSchema,
  SDKStreamlinedToolUseSummaryMessageSchema,
  SDKPermissionDenialSchema,
  SDKResultSuccessSchema,
  SDKResultErrorSchema,
  SDKResultMessageSchema,
  SDKSystemMessageSchema,
  SDKPartialAssistantMessageSchema,
  SDKCompactBoundaryMessageSchema,
  SDKStatusMessageSchema,
  SDKPostTurnSummaryMessageSchema,
  SDKAPIRetryMessageSchema,
  SDKLocalCommandOutputMessageSchema,
  SDKHookStartedMessageSchema,
  SDKHookProgressMessageSchema,
  SDKHookResponseMessageSchema,
  SDKToolProgressMessageSchema,
  SDKAuthStatusMessageSchema,
  SDKFilesPersistedEventSchema,
  SDKTaskNotificationMessageSchema,
  SDKTaskStartedMessageSchema,
  SDKSessionStateChangedMessageSchema,
  SDKTaskProgressMessageSchema,
  SDKToolUseSummaryMessageSchema,
  SDKElicitationCompleteMessageSchema,
  SDKPromptSuggestionMessageSchema,
  SDKSessionInfoSchema,
  SDKMessageSchema,
  FastModeStateSchema,
} from './coreSchemas.js'

type InferSchema<S extends () => z.ZodTypeAny> = z.infer<ReturnType<S>>

export type ModelUsage = InferSchema<typeof ModelUsageSchema>
export type OutputFormatType = InferSchema<typeof OutputFormatTypeSchema>
export type BaseOutputFormat = InferSchema<typeof BaseOutputFormatSchema>
export type JsonSchemaOutputFormat = InferSchema<typeof JsonSchemaOutputFormatSchema>
export type OutputFormat = InferSchema<typeof OutputFormatSchema>
export type ApiKeySource = InferSchema<typeof ApiKeySourceSchema>
export type ConfigScope = InferSchema<typeof ConfigScopeSchema>
export type SdkBeta = InferSchema<typeof SdkBetaSchema>
export type ThinkingAdaptive = InferSchema<typeof ThinkingAdaptiveSchema>
export type ThinkingEnabled = InferSchema<typeof ThinkingEnabledSchema>
export type ThinkingDisabled = InferSchema<typeof ThinkingDisabledSchema>
export type ThinkingConfig = InferSchema<typeof ThinkingConfigSchema>
export type McpStdioServerConfig = InferSchema<typeof McpStdioServerConfigSchema>
export type McpSSEServerConfig = InferSchema<typeof McpSSEServerConfigSchema>
export type McpHttpServerConfig = InferSchema<typeof McpHttpServerConfigSchema>
export type McpSdkServerConfig = InferSchema<typeof McpSdkServerConfigSchema>
export type McpServerConfigForProcessTransport = InferSchema<typeof McpServerConfigForProcessTransportSchema>
export type McpClaudeAIProxyServerConfig = InferSchema<typeof McpClaudeAIProxyServerConfigSchema>
export type McpServerStatusConfig = InferSchema<typeof McpServerStatusConfigSchema>
export type McpServerStatus = InferSchema<typeof McpServerStatusSchema>
export type McpSetServersResult = InferSchema<typeof McpSetServersResultSchema>
export type PermissionUpdateDestination = InferSchema<typeof PermissionUpdateDestinationSchema>
export type PermissionBehavior = InferSchema<typeof PermissionBehaviorSchema>
export type PermissionRuleValue = InferSchema<typeof PermissionRuleValueSchema>
export type PermissionUpdate = InferSchema<typeof PermissionUpdateSchema>
export type PermissionDecisionClassification = InferSchema<typeof PermissionDecisionClassificationSchema>
export type PermissionResult = InferSchema<typeof PermissionResultSchema>
export type PermissionMode = InferSchema<typeof PermissionModeSchema>
export type HookEvent = InferSchema<typeof HookEventSchema>
export type BaseHookInput = InferSchema<typeof BaseHookInputSchema>
export type PreToolUseHookInput = InferSchema<typeof PreToolUseHookInputSchema>
export type PermissionRequestHookInput = InferSchema<typeof PermissionRequestHookInputSchema>
export type PostToolUseHookInput = InferSchema<typeof PostToolUseHookInputSchema>
export type PostToolUseFailureHookInput = InferSchema<typeof PostToolUseFailureHookInputSchema>
export type PermissionDeniedHookInput = InferSchema<typeof PermissionDeniedHookInputSchema>
export type NotificationHookInput = InferSchema<typeof NotificationHookInputSchema>
export type UserPromptSubmitHookInput = InferSchema<typeof UserPromptSubmitHookInputSchema>
export type SessionStartHookInput = InferSchema<typeof SessionStartHookInputSchema>
export type SetupHookInput = InferSchema<typeof SetupHookInputSchema>
export type StopHookInput = InferSchema<typeof StopHookInputSchema>
export type StopFailureHookInput = InferSchema<typeof StopFailureHookInputSchema>
export type SubagentStartHookInput = InferSchema<typeof SubagentStartHookInputSchema>
export type SubagentStopHookInput = InferSchema<typeof SubagentStopHookInputSchema>
export type PreCompactHookInput = InferSchema<typeof PreCompactHookInputSchema>
export type PostCompactHookInput = InferSchema<typeof PostCompactHookInputSchema>
export type TeammateIdleHookInput = InferSchema<typeof TeammateIdleHookInputSchema>
export type TaskCreatedHookInput = InferSchema<typeof TaskCreatedHookInputSchema>
export type TaskCompletedHookInput = InferSchema<typeof TaskCompletedHookInputSchema>
export type ElicitationHookInput = InferSchema<typeof ElicitationHookInputSchema>
export type ElicitationResultHookInput = InferSchema<typeof ElicitationResultHookInputSchema>
export type ConfigChangeHookInput = InferSchema<typeof ConfigChangeHookInputSchema>
export type InstructionsLoadedHookInput = InferSchema<typeof InstructionsLoadedHookInputSchema>
export type WorktreeCreateHookInput = InferSchema<typeof WorktreeCreateHookInputSchema>
export type WorktreeRemoveHookInput = InferSchema<typeof WorktreeRemoveHookInputSchema>
export type CwdChangedHookInput = InferSchema<typeof CwdChangedHookInputSchema>
export type FileChangedHookInput = InferSchema<typeof FileChangedHookInputSchema>
export type ExitReason = InferSchema<typeof ExitReasonSchema>
export type SessionEndHookInput = InferSchema<typeof SessionEndHookInputSchema>
export type HookInput = InferSchema<typeof HookInputSchema>
export type AsyncHookJSONOutput = InferSchema<typeof AsyncHookJSONOutputSchema>
export type PreToolUseHookSpecificOutput = InferSchema<typeof PreToolUseHookSpecificOutputSchema>
export type UserPromptSubmitHookSpecificOutput = InferSchema<typeof UserPromptSubmitHookSpecificOutputSchema>
export type SessionStartHookSpecificOutput = InferSchema<typeof SessionStartHookSpecificOutputSchema>
export type SetupHookSpecificOutput = InferSchema<typeof SetupHookSpecificOutputSchema>
export type SubagentStartHookSpecificOutput = InferSchema<typeof SubagentStartHookSpecificOutputSchema>
export type PostToolUseHookSpecificOutput = InferSchema<typeof PostToolUseHookSpecificOutputSchema>
export type PostToolUseFailureHookSpecificOutput = InferSchema<typeof PostToolUseFailureHookSpecificOutputSchema>
export type PermissionDeniedHookSpecificOutput = InferSchema<typeof PermissionDeniedHookSpecificOutputSchema>
export type NotificationHookSpecificOutput = InferSchema<typeof NotificationHookSpecificOutputSchema>
export type PermissionRequestHookSpecificOutput = InferSchema<typeof PermissionRequestHookSpecificOutputSchema>
export type CwdChangedHookSpecificOutput = InferSchema<typeof CwdChangedHookSpecificOutputSchema>
export type FileChangedHookSpecificOutput = InferSchema<typeof FileChangedHookSpecificOutputSchema>
export type SyncHookJSONOutput = InferSchema<typeof SyncHookJSONOutputSchema>
export type ElicitationHookSpecificOutput = InferSchema<typeof ElicitationHookSpecificOutputSchema>
export type ElicitationResultHookSpecificOutput = InferSchema<typeof ElicitationResultHookSpecificOutputSchema>
export type WorktreeCreateHookSpecificOutput = InferSchema<typeof WorktreeCreateHookSpecificOutputSchema>
export type HookJSONOutput = InferSchema<typeof HookJSONOutputSchema>
export type PromptRequestOption = InferSchema<typeof PromptRequestOptionSchema>
export type PromptRequest = InferSchema<typeof PromptRequestSchema>
export type PromptResponse = InferSchema<typeof PromptResponseSchema>
export type SlashCommand = InferSchema<typeof SlashCommandSchema>
export type AgentInfo = InferSchema<typeof AgentInfoSchema>
export type ModelInfo = InferSchema<typeof ModelInfoSchema>
export type AccountInfo = InferSchema<typeof AccountInfoSchema>
export type AgentMcpServerSpec = InferSchema<typeof AgentMcpServerSpecSchema>
export type AgentDefinition = InferSchema<typeof AgentDefinitionSchema>
export type SettingSource = InferSchema<typeof SettingSourceSchema>
export type SdkPluginConfig = InferSchema<typeof SdkPluginConfigSchema>
export type RewindFilesResult = InferSchema<typeof RewindFilesResultSchema>
export type APIUserMessagePlaceholder = InferSchema<typeof APIUserMessagePlaceholder>
export type APIAssistantMessagePlaceholder = InferSchema<typeof APIAssistantMessagePlaceholder>
export type RawMessageStreamEventPlaceholder = InferSchema<typeof RawMessageStreamEventPlaceholder>
export type UUIDPlaceholder = InferSchema<typeof UUIDPlaceholder>
export type NonNullableUsagePlaceholder = InferSchema<typeof NonNullableUsagePlaceholder>
export type SDKAssistantMessageError = InferSchema<typeof SDKAssistantMessageErrorSchema>
export type SDKStatus = InferSchema<typeof SDKStatusSchema>
export type SDKUserMessage = InferSchema<typeof SDKUserMessageSchema>
export type SDKUserMessageReplay = InferSchema<typeof SDKUserMessageReplaySchema>
export type SDKRateLimitInfo = InferSchema<typeof SDKRateLimitInfoSchema>
export type SDKAssistantMessage = InferSchema<typeof SDKAssistantMessageSchema>
export type SDKRateLimitEvent = InferSchema<typeof SDKRateLimitEventSchema>
export type SDKStreamlinedTextMessage = InferSchema<typeof SDKStreamlinedTextMessageSchema>
export type SDKStreamlinedToolUseSummaryMessage = InferSchema<typeof SDKStreamlinedToolUseSummaryMessageSchema>
export type SDKPermissionDenial = InferSchema<typeof SDKPermissionDenialSchema>
export type SDKResultSuccess = InferSchema<typeof SDKResultSuccessSchema>
export type SDKResultError = InferSchema<typeof SDKResultErrorSchema>
export type SDKResultMessage = InferSchema<typeof SDKResultMessageSchema>
export type SDKSystemMessage = InferSchema<typeof SDKSystemMessageSchema>
export type SDKPartialAssistantMessage = InferSchema<typeof SDKPartialAssistantMessageSchema>
export type SDKCompactBoundaryMessage = InferSchema<typeof SDKCompactBoundaryMessageSchema>
export type SDKStatusMessage = InferSchema<typeof SDKStatusMessageSchema>
export type SDKPostTurnSummaryMessage = InferSchema<typeof SDKPostTurnSummaryMessageSchema>
export type SDKAPIRetryMessage = InferSchema<typeof SDKAPIRetryMessageSchema>
export type SDKLocalCommandOutputMessage = InferSchema<typeof SDKLocalCommandOutputMessageSchema>
export type SDKHookStartedMessage = InferSchema<typeof SDKHookStartedMessageSchema>
export type SDKHookProgressMessage = InferSchema<typeof SDKHookProgressMessageSchema>
export type SDKHookResponseMessage = InferSchema<typeof SDKHookResponseMessageSchema>
export type SDKToolProgressMessage = InferSchema<typeof SDKToolProgressMessageSchema>
export type SDKAuthStatusMessage = InferSchema<typeof SDKAuthStatusMessageSchema>
export type SDKFilesPersistedEvent = InferSchema<typeof SDKFilesPersistedEventSchema>
export type SDKTaskNotificationMessage = InferSchema<typeof SDKTaskNotificationMessageSchema>
export type SDKTaskStartedMessage = InferSchema<typeof SDKTaskStartedMessageSchema>
export type SDKSessionStateChangedMessage = InferSchema<typeof SDKSessionStateChangedMessageSchema>
export type SDKTaskProgressMessage = InferSchema<typeof SDKTaskProgressMessageSchema>
export type SDKToolUseSummaryMessage = InferSchema<typeof SDKToolUseSummaryMessageSchema>
export type SDKElicitationCompleteMessage = InferSchema<typeof SDKElicitationCompleteMessageSchema>
export type SDKPromptSuggestionMessage = InferSchema<typeof SDKPromptSuggestionMessageSchema>
export type SDKSessionInfo = InferSchema<typeof SDKSessionInfoSchema>
export type SDKMessage = InferSchema<typeof SDKMessageSchema>
export type FastModeState = InferSchema<typeof FastModeStateSchema>
