/**
 * Generates `src/entrypoints/sdk/coreTypes.generated.ts` from Zod lazy schemas
 * in `coreSchemas.ts`. Run: `bun scripts/generate-sdk-types.ts`
 */
import { readFileSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')
const coreSchemasPath = join(root, 'src/entrypoints/sdk/coreSchemas.ts')
const outPath = join(root, 'src/entrypoints/sdk/coreTypes.generated.ts')

const src = readFileSync(coreSchemasPath, 'utf8')
const re = /^export const (\w+) = lazySchema/gm
const names: string[] = []
let m: RegExpExecArray | null
while ((m = re.exec(src)) !== null) {
  names.push(m[1]!)
}

const header = `// AUTO-GENERATED by scripts/generate-sdk-types.ts — do not edit by hand.
import type { z } from 'zod/v4'
import {
${names.map(n => `  ${n},`).join('\n')}
} from './coreSchemas.js'

type InferSchema<S extends () => z.ZodTypeAny> = z.infer<ReturnType<S>>

`

const body = names
  .map(schemaName => {
    const typeName = schemaName.replace(/Schema$/, '')
    return `export type ${typeName} = InferSchema<typeof ${schemaName}>`
  })
  .join('\n')

writeFileSync(outPath, `${header}${body}\n`, 'utf8')
console.log(`Wrote ${names.length} types to ${outPath}`)
